---
- hosts: localhost
  roles:
          - name: "Creating Master instance"
            role: aws_instance_launcher
            vars:
                    i_name: kk_master
                    access_pass: AKIYYLPPOFNCRT2W
                    secret_pass: e33HrqVMMTsS53RxbXjbIerUjXj
                    grp_tag: kk_master
                    tag: master
