---
# tasks file for kubernetes-slave-setup---
- name: "yum configure"
  yum_repository:
            name: "kubernetes"
            description: "kubernetes repo"
            baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
            enabled: yes
            gpgcheck: yes
            repo_gpgcheck: yes
            gpgkey:
                - https://packages.cloud.google.com/yum/doc/yum-key.gpg
                - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
           #exclude: kubelet kubeadm kubectl
- name: "Installing required packages "
  package:
            name:
                    - docker
                    - kubelet
                    - kubeadm
                    - iproute-tc
                    - kubectl
  
- name: "docker con"
  copy:
            dest: /etc/docker/daemon.json
            content: '{
                         "exec-opts": ["native.cgroupdriver=systemd"]
                     }'
  notify: restart docker 

- name: "services"
  service:
            name: "{{ item }}"
            state: started
            enabled: yes
  loop: 
      - docker
      - kubelet

- name: "docker con"
  copy:
            dest: /etc/sysctl.d/k8s.conf
            src: bridge.yml
- name: "Pulling Images"
  shell:
            cmd: "sysctl --system"
- name: "Copying Token"
  copy:
            src: "/token.txt"
            dest: "~/token.txt"
- name: "Creating Token"
  shell:
            cmd: "bash ~/token.txt "
